### ISSUE TITLE
Örnek Veriler

### ISSUE THREAD

**Issue by MRTBSKTP** [utahemre/GeojsonServer#1]
İyi günler dilerim, BTK akademi üzerinden "Web Tabanlı Coğrafi Bilgi Sistemleri" eğitiminiz takip etmekteyim. Örnek verileri postgresqle yükleme videosuna kadar geldim fakat sizin kullandığınız örnek verilere nereden ulaşabileceğimi bulamadım acaba onları bu repoya geojson veya başka bir formatta eklemeniz mümkün mü? Şimdiden teşekkür ederim

**Comment by utahemre** [comment]
Eğitimin dokümanlar kısmındaki pdf dosyasında link mevcut.
